edit workspace

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -99,25 +99,47 @@ jobs:
         with:
           name: checkov-report
           path: ./terraform/checkov-report.json
+      - name: Install Checkov
+        run: pip install checkov
 
+      - name: Run Checkov HTML Report
+        run: checkov -d . --output html > checkov-report.html
+
+      - name: Upload Checkov HTML Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: checkov-html-report
+          path: ./terraform/checkov-report.html
       - name: Show Checkov CLI summary
         run: checkov -d . --output cli
 
-
-      # Apply or Destroy only on manual trigger
-      - name: Terraform Apply or Destroy
-        if: github.event_name == 'workflow_dispatch'
+      - name: Terraform Apply
         run: |
-          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
-            terraform destroy -var-file="${{ github.event.inputs.env }}.tfvars" -auto-approve
-          else
-            terraform apply -var-file="${{ github.event.inputs.env }}.tfvars" -auto-approve -input=false -parallelism=10 tfplan
-          fi
+          terraform apply -var-file="dev.tfvars" -auto-approve -input=false -parallelism=10 tfplan
 
-      - name: Fail if apply/destroy failed
-        if: github.event_name == 'workflow_dispatch' && failure()
+      - name: Fail if apply failed
+        if: failure()
         run: exit 1
 
       - name: Terraform Output
-        if: github.event_name == 'workflow_dispatch' && success()
+        if: success()
         run: terraform output -json > output.json
+
+
+      # # Apply or Destroy only on manual trigger
+      # - name: Terraform Apply or Destroy
+      #   if: github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+      #       terraform destroy -var-file="${{ github.event.inputs.env }}.tfvars" -auto-approve
+      #     else
+      #       terraform apply -var-file="${{ github.event.inputs.env }}.tfvars" -auto-approve -input=false -parallelism=10 tfplan
+      #     fi
+
+      # - name: Fail if apply/destroy failed
+      #   if: github.event_name == 'workflow_dispatch' && failure()
+      #   run: exit 1
+
+      # - name: Terraform Output
+      #   if: github.event_name == 'workflow_dispatch' && success()
+      #   run: terraform output -json > output.json
